### ISSUE TITLE
v0.1 Roadmap

### ISSUE THREAD

**Issue by utilForever** [utilForever/phys#5]
- [ ] Implement basic geometry types
  - [ ] Vector
  - [ ] Matrix
- [ ] Implement particle physics
  - [ ] Particle
    - [ ] The force equations
    - [ ] Adding mass to particles
    - [ ] Momentum and velocity
    - [ ] The force of gravity
    - [ ] The update equations
    - [ ] The complete integrator
  - [ ] Examples
    - [ ] Ballistics
    - [ ] Fireworks
